### PR TITLE
Add a preference for selecting a different Matlab version

### PR DESCRIPTION
**Pull request by toeklk**
Add a preference for selecting a different matlab version.

Known issues:
- The preference is always visible, even if matlab control is not used
- No tests
- No documentation

Tested on mac os X (worksforme).

Important Disclaimer: I’m not a java programmer…

Signed-off-by: Klaas Gadeyne <klaas.gadeyne@gmail.com>

### CODE REVIEW

**Comment by abelhegedus** [comment]
This seems to be a useful contribution, thanks!

However, I have a couple of comments and suggestions which I will add to the commit.

**Comment by abelhegedus** [comment]
Okay, the code looks fine. Since the code is under EPL, can you state the following before we merge this:

* Did you author 100% of the content?
* Do you have the rights to contribute this content to Massif?
* Is the contribution under the Eclipse Public License?

**Comment by abelhegedus** [comment]
Additionally, if you prefer, you could add your name as contributor in the header comment of files that you changes significantly.

**Comment by toeklk** [comment]
a. I, Klaas Gadeyne, wrote 100% of the code I've provided.
b. I have the right to contribute the code to Eclipse.
c. I contribute the content under the EPL.
d. This contribution contains no Cryptography features.

**Pull request merged**
